#!/usr/bin/env bash
# Installs Ngix andshould be listening on port 80
# Serve a page that would return a Hello World string

echo "###First Updating and installation follows.\n"
sudo apt-get update -y && 
	sudo apt-get install nginx -y
echo "----Getting system ready----\n"

#Starting new nginx serve
echo "---Nginx is starting---"
sudo service nginx start

#allowing Nginx on firewall
read -p "Do you want to allow Nginx through the firewall? (yes/no): " choice
if [[ $choice == "yes" ]]; then
	sudo ufw allow 'Nginx HTTP'
	echo "Nginx has been allowed through the firewall.\n"
elif [[ $choice == "no" ]]; then
	echo "Nginx will not be allowed through the firewall\n."
else
	echo "Invalid choice. Please enter 'yes' or 'no'.\n"
fi

#Allow ownership to the website file for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

#Backup index at default
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

#New Index
echo "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html

#Restarting Nginx
echo "---Nginx is restarting---\n"
sudo service nginx restart

echo "---Nginx installation Complete---\n"
