#!/usr/bin/env bash
#Prints an IP address passed as an argument.
#+ Accepts a string as an argument
#it also displays "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
#+ if no argument is passed
#Pings the IP 5 times
if [$# -eq 0]
then
echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
ping -c 5 "$1"
fi
