#!/usr/bin/env bash
#Displays 'To infinity and beyond' with
#+ a sleep 2 in between each iteration
#Displays 'I am Invincible6'
trap 'echo "I am invincible!!!"' SIGTERM
while true; do
	echo "To Infinity and beyond"
	sleep 2
done
