#!/usr/bin/env bash
#Displays numbers from 1 to 20 and:
#+ displays 4 and then bad luck from China
#+ displays 9 and then bad luck from Japan
#+ displays 17 and then bad_luck from Italy

loop=1
while [ $loop -le 20]
do
	echo "$loop"
	case $loop in
		"4") echo "bad luck from China";;
		"5") echo "bad luck from Japan";;
		"17") echo "bad luck from Italy";;
	esac
	(( loop++ ))
done
