#!/usr/bin/env bash
#Displays all active IPs on the machine it's executed on
#Note that IPs may vary depending on which machine the script runs on

ifconfig | grep -Eo "inet (addr:)?([0-9]*\.){3}[0-9]*" | cut -b 11-
